import express        from 'express';
import cors           from 'cors';
import helmet         from 'helmet';
import compression    from 'compression';
import morgan         from 'morgan';
import cookieParser   from 'cookie-parser';
import passport       from './config/passport';
import { globalLimiter } from './middlewares/rateLimiter.middleware';
import { errorHandler, notFoundHandler } from './middlewares/error.middleware';

import authRoutes          from './routes/auth.routes';
import postsRoutes         from './routes/posts.routes';
import usersRoutes         from './routes/users.routes';
import notificationsRoutes from './routes/notifications.routes';
import messagesRoutes      from './routes/messages.routes';
import communitiesRoutes   from './routes/communities.routes';
import analyticsRoutes     from './routes/analytics.routes';
import moderationRoutes    from './routes/moderation.routes';
import debatesRoutes       from './routes/debates.routes';
import spacesRoutes        from './routes/spaces.routes';
import mediaRoutes         from './routes/media.routes';
import privacyRoutes       from './routes/privacy.routes';
import narrativeRoutes     from './routes/narrative.routes';
import translationRoutes   from './routes/translation.routes';
import communityModRoutes  from './routes/community-mod.routes';
import listsRoutes         from './routes/lists.routes';
import billingRoutes       from './routes/billing.routes';
import monetizationRoutes  from './routes/monetization.routes';
import complianceRoutes    from './routes/compliance.routes';
import aiRoutes            from './routes/ai.routes';
import oauthRoutes         from './routes/oauth.routes';
import meRoutes            from './routes/me.routes';
//import storiesRoutes       from './routes/stories.routes';
//import searchRoutes        from './routes/search.routes';
//import organizationsRoutes from './routes/organizations.routes';
//import webhooksRoutes      from './routes/webhooks.routes';

const app = express();
app.set('trust proxy', 1);

app.use(helmet({ contentSecurityPolicy: false, crossOriginEmbedderPolicy: false }));
app.use(cors({ origin: process.env.FRONTEND_URL || 'https://nexus-web-bjks.onrender.com', credentials: true }));
app.use(compression());
app.use(morgan('combined'));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(passport.initialize());
app.use(globalLimiter);

app.use('/api/auth',          authRoutes);
app.use('/api/auth',          oauthRoutes);
app.use('/api/users/me',      meRoutes);
app.use('/api/posts',         postsRoutes);
app.use('/api/users',         usersRoutes);
app.use('/api/notifications', notificationsRoutes);
app.use('/api/messages',      messagesRoutes);
app.use('/api/communities',   communitiesRoutes);
app.use('/api/analytics',     analyticsRoutes);
app.use('/api/moderation',    moderationRoutes);
app.use('/api/debates',       debatesRoutes);
app.use('/api/spaces',        spacesRoutes);
app.use('/api/media',         mediaRoutes);
app.use('/api/privacy',       privacyRoutes);
app.use('/api/narrative',     narrativeRoutes);
app.use('/api/translate',     translationRoutes);
app.use('/api/community-mod', communityModRoutes);
app.use('/api/lists',         listsRoutes);
app.use('/api/billing',       billingRoutes);
app.use('/api/monetization',  monetizationRoutes);
app.use('/api/compliance',    complianceRoutes);
app.use('/api/ai',            aiRoutes);
//app.use('/api/stories',       storiesRoutes);
//app.use('/api/search',        searchRoutes);
//app.use('/api/organizations', organizationsRoutes);
//app.use('/api/webhooks',      webhooksRoutes);

app.use(notFoundHandler);
app.use(errorHandler);

export default app;
